services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
    command: npm run dev
#   db:
#     image: postgres:15
#     container_name: turnero_db
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: turnero
#     ports:
#       - "5432:5432"
#*    Esto hace que se guarden los datos (en este caso los de postgresql) en mi computadora en el caso que se borren
#     volumes:
#       - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:
